version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "s3://loginapp532"
        BUILD_FOLDER: "dist"
phases:
  install:
    runtime-versions:
        nodejs: 10
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
        - echo Dependencies installation completed
  build:
    commands:
        - echo Build started for the Project, Please wait...
        - ng build
        - echo Build Completed
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
